apiVersion: v1
kind: Secret
metadata:
  name: taskcal-secrets
  namespace: default
type: Opaque
stringData:
  JWT_SECRET: 
  MONGO_URI: 
  REDIS_USERNAME: 
  REDIS_PASSWORD:
  REDIS_HOST: 
  REDIS_PORT:
  RESEND_API_KEY: 
  RESEND_FROM_EMAIL:
  CLIENT_URL:
  NOTIFICATION_SERVICE:
